### ISSUE TITLE
EventHandler is not being called using EventProvider

### ISSUE THREAD

**Issue by josecelano** [josecelano/ddd-symfony-sample#1]
In RegisterUserCommandHandler:

```
        $event = new UserWasRegisteredEvent('username');
        $this->eventProvider->raise($event);
```

UserWasRegisteredEvent is raised but SendNotificationMailAfterUserWasRegistered (EventHandler) is never called.

Service configuration

```
    matthias_user_app_infraestructure_command.notification_mail_event_handler:
        class: Matthias\User\App\Event\SendNotificationMailAfterUserWasRegistered
        tags:
            - { name: event_subscriber, subscribes_to: user_was_registered }
```

This is waht I am trying to do:

http://php-and-symfony.matthiasnoback.nl/2015/01/collecting-events-and-the-events-aware-command-bus/

**Comment by josecelano** [comment]
Fixed. Added tags.

```
    matthias_user_app_infraestructure_command.event_provider:
        class: Matthias\User\App\Event\EventProvider
        tags:
            - { name: event_provider }
```
